export enum JobPriorityEnum {
  FIRST_HARVESTER = 1000,
  FIRST_HAULER = 900,
  PRIMARY_ROOM_HARVESTER = 800,
  PRIMARY_ROOM_HAULER = 800,
  FIRST_BUILDER = 600,
  FIRST_UPGRADER = 550,
  REMOTE_SOURCE_HARVESTER = 400,
  REMOTE_SOURCE_HAULER = 350
}
