export enum PriorityEnum {
  FIRST_HARVESTER = 100,
  FIRST_HAULER = 90,
  PRIMARY_ROOM_HARVESTER = 80,
  PRIMARY_ROOM_HAULER = 75,
  FIRST_BUILDER = 60,
  FIRST_UPGRADER = 55,
  REMOTE_SOURCE_HARVESTER = 40,
  REMOTE_SOURCE_HAULER = 35,
}
